name: Testing some docker hub deployment
description: Running a CI/CD workflow

on:
  push:
    branches: main
  workflow_dispatch:

concurrency:
  group: CI/CD
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Building the docker file into an image
        run: echo docker build -t ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }} /${{ vars.IMAGE_NAME }}:latest

      - name: Docker Login
        run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Docker
        run: echo docker push ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:lastest

  deploy:
    timeout-minutes: 5
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run the image
        run: echo docker run -d -p 8000:8000 ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest
